### PR TITLE
Moved changes to DEV

### PR DESCRIPTION
**Pull request by DesperateProgrammer**

### CODE REVIEW

**Comment by gsker** [comment]
I can't figure out github, but I want to know how you got the number 0x13FFF to add to the size of the 0x10000.bin file to determine where to flash the image.

I have used the numbers and they work!!! Thank you. 

echo "scale=0; obase=16; ( $binfilesize + 81919 )/16384 \* 16384" | bc -q
81919 is 0x13FFF

But now I want to know why that one works.
If there's another place this should be discussed, let me know!

EDIT: But if I don't use your tree, that number doesn't work. :-(  If I do a build from upstream:dev if I create a filesystem and put it at 0x78000 then the firmware no longer starts.  
Where are the docs that say where the filesystem ends up after flashing the firmware? Also, how do we prevent the firmware from doing a file.format() when it comes up for the first time?

**Comment by DesperateProgrammer** [comment]
Hello @gsker,

I'm not good with git either, but i can answer your question:

The filesystem has to be at the next free page boundary after the irom0 image. This is the one placed at 0x10000.
The last byte of this image will be placed at BaseAddress + LengthOfImage - 1
The byte  at BaseAddress + LengthOfImage - 1 + pagesize therefor has to be in the next page and thus is in the first free page. If you replace the variables with their values you get
0x10000+ LengthOfImage - 1 + 0x4000 and this is LengthOfImage + 0x13FFF

The div and mul in integer number space will then just drop the last 12 bits of this address and thus give you the base address of the first free page base address, where the FS requires to be.

Regarding your edit: It seems that you forgot the 0x10000 to and just used only 0x3FFF (0x7800 does seem around the size of teh dev irom0 image. You have not flashed the image after the firmware but in the middle of it and have overwitten valid code.

**Comment by gsker** [comment]
Thanks for the reply and good explanation.

0x13FFF is 81919 decimal so it should include the 0x10000 and the 0x3FFF, right?
0x74000 is the size I used with the image on your build. (which is what I mean when I said it worked). 
I used  0x78000 (not 0x7800 ...) for the dev build.  
(This is 1.5.1, btw) 

My image is 411,008 bytes long
Here's my calculation:

~> echo $(( ((0x10000 + 411008 -1 +0x4000) / 0x4000) \* 0x4000 ))
491520

and the bc output:
obase=16
491520
78000

And I flashed it like this:
esptool.py -b 345600 write_flash 0x78000 luafiles.img

So I have to believe that the filesystem for my firmware isn't in that location.  
I wonder how I could find out where it is.  
Is there a magic number at the beginning of the fileystem?  
I guess I could create a file and then dump the flash for the data. 
And if you see anything else wrong with my calculation, please let me know.

Is the pagesize different?

**Comment by gsker** [comment]
I flashed a clean image on the esp8266 and created a file in the file system. Then I extracted  0x78000 for 0x4000 bytes off the flash on the esp8266 and saved it in a file. 
This file starts with this sequence:
    00000000: 0000 0100 0100 0100 0000 0180 ffff ffff  ................
And that is followed until 0x100 with ffffs.
At 0x00100 I see a filename:
  00000100: 0180 0000 7800 0100 0001 6675 6e63 2e6c  ....x.....func.l

Contrast that with the file created by spiffsimg:
It has ffff from the beginning until 0x10FE (2 before 1100) where there is a 0200 and then there are ffffs until 0x2000 where there appears to be a header:
    00002000: 0100 0100 0100 0180 0200 0280 0300 0300  ................
    00002010: 0300 0300 0300 0000 0300 0380 ffff ffff  ................

So I would say there's some kind of alignment issue.  If 0x78000 was the right number then it should have looked a lot like the spiffs file system image created by spiffsimg -f luafiles.img -c  should have found the beginning of a spiffs file system there, right?  But I don't know what that even means.  I haven't dug into the file system structures yet.
The spiffsimg command from the DiUS github has more options. Perhaps some of them should be filled it.....
Anyway I'm still scratching my head.

**Pull request merged**
